#=
Printing: cohomology groups, cup product multiplication tables, a guess at a
ring presentation, and the two sanity checks every cohomology ring must pass
(the degree-0 class is a unit, and the product is graded commutative).
=#

### -------------------------------------------------------------------------
### Formatting
### -------------------------------------------------------------------------

"Short name for a coefficient ring: `Z`, `Q`, `F_2`, ..."
function ring_symbol(R)
  R === ZZ && return "Z"
  R === QQ && return "Q"
  if R isa Oscar.AbstractAlgebra.Field && !is_zero(characteristic(R))
    p = characteristic(R)
    d = applicable(degree, R) ? Int(degree(R)) : 1
    return d == 1 ? "F_$p" : "F_$(p)^$d"
  end
  return string(R)
end

"`Z^2 + Z/2` and friends; `0` for the trivial group."
function group_symbol(R, orders)
  sym = ring_symbol(R)
  isempty(orders) && return "0"
  free = count(is_zero, orders)
  parts = String[]
  free == 1 && push!(parts, sym)
  free > 1 && push!(parts, "$sym^$free")
  for m in orders
    is_zero(m) || push!(parts, "$sym/$m")
  end
  return join(parts, " + ")
end

"`2*x1_1 + x1_2`, `-x2`, `0`."
function format_combination(labels::Vector{String}, cs)
  isempty(cs) && return "0"
  terms = String[]
  for (j, c) in enumerate(cs)
    is_zero(c) && continue
    if is_one(c)
      push!(terms, labels[j])
    elseif string(c) == "-1"
      push!(terms, "-" * labels[j])
    else
      push!(terms, "$c*$(labels[j])")
    end
  end
  isempty(terms) && return "0"
  return replace(join(terms, " + "), " + -" => " - ")
end

format_combination(X::CohomologyRing, d::Int, cs) =
  format_combination(graded_basis(X, d).labels, cs)

"Label of a basis class, e.g. `x2_1`."
class_label(X::CohomologyRing, (d, j)::Tuple{Int,Int}) = graded_basis(X, d).labels[j]

### -------------------------------------------------------------------------
### Multiplication table
### -------------------------------------------------------------------------

"""
    cup_product_table(X) -> (rowcols, entries)

`rowcols` lists every canonical basis class as `(degree, index)`; `entries` is
the matrix of formatted products. A product landing above the top degree is `0`,
since `H^d = 0` for `d > dim K`.
"""
function cup_product_table(X::CohomologyRing)
  idx = basis_indices(X)
  n = length(idx)
  entries = fill("0", n, n)
  for (r, a) in enumerate(idx)
    check_deadline(X.deadline, "$(X.name): cup product table row $r/$n")
    for (c, b) in enumerate(idx)
      a[1] + b[1] > top_degree(X) && continue
      entries[r, c] = format_combination(X, a[1] + b[1], cup(X, a, b))
    end
  end
  return idx, entries
end

### -------------------------------------------------------------------------
### Ring identification
### -------------------------------------------------------------------------

"""
    identify_ring(X) -> Union{String,Nothing}

If `H^*` is generated by a single class `t`, return a presentation string such
as `Z[x2]/(x2^3),  |x2| = 2`; otherwise `nothing`. The generator is named
after its label in the table.

Detection: find the lowest positive degree `e` carrying a class, require every
`H^d` to be zero unless `e | d`, require each `H^(k*e)` to be cyclic and
generated by `t^k`, and record the order of `t` as an extra relation when it is
finite (that is what distinguishes, say, `Z[x2]/(2*x2, x2^3)` for `RP^4` from
`Z[x2]/(x2^3)` for `CP^2`).
"""
function identify_ring(X::CohomologyRing)
  sym = ring_symbol(X.coeff_ring)
  length(graded_basis(X, 0)) == 1 || return nothing
  top = top_degree(X)
  positive = [d for d in 1:top if !isempty(graded_basis(X, d).elems)]
  isempty(positive) && return sym          # the point
  e = minimum(positive)
  m = top ÷ e
  for d in 1:top
    want = (d % e == 0 && d <= m * e) ? 1 : 0
    length(graded_basis(X, d)) == want || return nothing
  end
  # t^k must generate H^(k*e).
  for k in 1:m
    c = cup_power(X, (e, 1), k)
    length(c) == 1 && is_unit(c[1]) || return nothing
  end
  g = graded_basis(X, e).labels[1]
  rels = String[]
  ord = graded_basis(X, e).orders[1]
  is_zero(ord) || push!(rels, "$(ord)*$g")
  push!(rels, "$g^$(m + 1)")
  return "$sym[$g]/($(join(rels, ", "))),  |$g| = $e"
end

### -------------------------------------------------------------------------
### Consistency checks
### -------------------------------------------------------------------------

"""
    check_ring(X) -> Vector{String}

Return a list of violated identities (empty means all good):

* the degree-0 generator acts as a unit;
* `a * b = (-1)^(|a| |b|) b * a` on cohomology.

Both are theorems about the cup product, so a failure means a bug here or
upstream, not a feature of the space.
"""
function check_ring(X::CohomologyRing)
  problems = String[]
  idx = basis_indices(X)
  if length(graded_basis(X, 0)) == 1
    u = (0, 1)
    for a in idx
      got = cup(X, u, a)
      want = [i == a[2] ? one(X.coeff_ring) : zero(X.coeff_ring) for i in 1:length(graded_basis(X, a[1]))]
      got == want || push!(problems, "$(class_label(X, u)) * $(class_label(X, a)) = " *
                                     format_combination(X, a[1], got) * ", expected $(class_label(X, a))")
    end
  end
  for a in idx
    check_deadline(X.deadline, "$(X.name): graded commutativity check")
    for b in idx
      a[1] + b[1] > top_degree(X) && continue
      ab = cup(X, a, b)
      ba = cup(X, b, a)
      sign = isodd(a[1] * b[1]) ? -1 : 1
      ords = graded_basis(X, a[1] + b[1]).orders
      ab == [_reduce(sign * c, m) for (c, m) in zip(ba, ords)] || push!(problems,
        "graded commutativity fails: $(class_label(X, a))*$(class_label(X, b)) = " *
        format_combination(X, a[1] + b[1], ab) * " but " *
        "$(class_label(X, b))*$(class_label(X, a)) = " *
        format_combination(X, a[1] + b[1], ba))
    end
  end
  return problems
end

### -------------------------------------------------------------------------
### The report
### -------------------------------------------------------------------------

"""
    print_report(io, X; note, checks, max_table)

Groups, cup product table, ring presentation and consistency checks.

`max_table` caps the size of the printed table. Both the table and the checks
are quadratic in the total number of basis classes, and some library entries
have very large cohomology -- `PG128_PG128P7` has `H^1` of rank 2541, so its
table would hold 6.5 million products. Above the cap the groups are still
reported and the table is skipped; use `cup(X, (p,i), (q,j))` for the products
you actually want.
"""
function print_report(io::IO, X::CohomologyRing; note::AbstractString = "",
                      checks::Bool = true, max_table::Int = 40)
  K = X.complex
  sym = ring_symbol(X.coeff_ring)
  title = "$(X.name)   coefficients in $sym"
  println(io, "=" ^ max(72, length(title)))
  println(io, title)
  isempty(note) || println(io, "  ($note)")
  println(io, "=" ^ max(72, length(title)))
  println(io, "simplicial model: dim = $(dim(K)), f-vector = $(f_vector(K))")
  println(io)

  println(io, "cohomology groups")
  for d in 0:top_degree(X)
    b = graded_basis(X, d)
    gens_str = isempty(b.labels) ? "" : "   basis: " * join(b.labels, ", ")
    println(io, "  H^$d = ", rpad(group_symbol(X.coeff_ring, b.orders), 20), gens_str)
  end
  println(io)

  idx = basis_indices(X)
  if length(idx) > max_table
    println(io, "cup product table: skipped -- $(length(idx)) basis classes ",
                "($(length(idx)^2) products) exceeds max_table = $max_table.")
    println(io, "  Use cup(X, (p, i), (q, j)) for individual products, or pass a larger max_table.")
    println(io)
    println(io, "ring structure: not attempted at this size")
    println(io)
    return nothing
  end
  idx, entries = cup_product_table(X)
  if isempty(idx)
    println(io, "cup product table: (no classes)")
  else
    heads = [class_label(X, a) for a in idx]
    w = max(maximum(length, heads), maximum(length, entries), 3) + 2
    println(io, "cup product table  (row * column)")
    println(io, "  " * lpad("", w) * "|" * join(lpad(h, w) for h in heads))
    println(io, "  " * "-" ^ (w + 1 + w * length(heads)))
    for r in eachindex(idx)
      println(io, "  " * lpad(heads[r], w) * "|" *
                  join(lpad(entries[r, c], w) for c in eachindex(idx)))
    end
  end
  println(io)

  pres = identify_ring(X)
  println(io, "ring structure: ", isnothing(pres) ?
    "not generated by a single class -- read it off the table above" : pres)

  if checks
    problems = check_ring(X)
    if isempty(problems)
      println(io, "checks: unit law and graded commutativity hold")
    else
      println(io, "checks: FAILED")
      for p in problems
        println(io, "  - ", p)
      end
    end
  end
  println(io)
  return nothing
end

print_report(X::CohomologyRing; kwargs...) = print_report(stdout, X; kwargs...)
